### ISSUE TITLE
Comprehensive Feature List for Current Sprint Delivery

### ISSUE THREAD

**Issue by iGotty** [UniSchedule/Wiki#105]
Compile and list all features scheduled for delivery in this sprint, including both new implementations and carry-over functionalities from Sprint 2. This will provide a clear overview of the sprint's objectives and deliverables for better tracking and team alignment.

**Comment by SnowArtz** [comment]
The Feature List for Current Sprint Delivery added in [wiki](https://github.com/ISIS3510-202410-Team-13/Wiki/wiki/S3_Final)
