### ISSUE TITLE
Define Eventual Connectivity Strategy for Multi Threading

### ISSUE THREAD

**Issue by SnowArtz** [UniSchedule/Wiki#110]
Design solutions with eventual connectivity strategies and argue your choices. You must describe which eventual connectivity scenarios are you going to manage. Moreover, you should describe your eventual connectivity scenarios and show how the app behaves on them

**Comment by iGotty** [comment]
Added in [wiki](https://github.com/ISIS3510-202410-Team-13/Wiki/wiki/S3_Final)
