### ISSUE TITLE
Document Micro-Optimizations

### ISSUE THREAD

**Issue by jsurrea** [UniSchedule/Wiki#123]
Design, implement and justify micro-optimization strategies within the app. For this, first evaluate the performance using the profiling tool before the micro-optimization implementation, then implement the optimization, finally use the profiling tool again to test the modified feature.

AC:
* At least 3 Micro-Optimizations are documented in the WIKI.

Since you  have  to  show  the  implementation  of  micro  optimization,  you  have  to  show your   code   and   the   results   on   the   profiling   tool   before   implementing   the   micro-optimization,  then  you  have  to  show  also  snippets  of  code  for  the  implementation  and also the results of the profiling tool

**Comment by SnowArtz** [comment]
It was already done at the wiki! We did GPU, Overdrawing and Memory Analysis of our App.
