### ISSUE TITLE
MS2: Make a list of 4 problems

### ISSUE THREAD

**Issue by iGotty** [UniSchedule/Wiki#16]
Make a list with the 4 problems that interested the team the most that came from the _Identifying Problems - Activity_

**Comment by jdcastellanosb73** [comment]
The problems that have interested us the most are:
 Schedule Coordination Problem,
 University Gastronomic Offer Problem,
 Campus Interactive Map Application Problem,
 Campus recicle and reuse problem.

This was docummentated at [Wiki problems List](https://github.com/ISIS3510-202410-Team-13/Wiki/wiki/S1_MS2#problems-that-interested-us-the-most)
