### ISSUE TITLE
Brainstorming Process ->Procedure->Proposed Solutions 

### ISSUE THREAD

**Issue by jdcastellanosb73** [UniSchedule/Wiki#33]
for this activity we started in a class taking notes of the ideas that we had, and how they can get better when we start creating the application

**Comment by SnowArtz** [comment]
The images of the braimstorming process were added, also the proposed solutions and the procedure we followed for arriving to those. This was documentated at: [Wiki-Braimstorm](https://github.com/ISIS3510-202410-Team-13/Wiki/wiki/S1_MS2#brainstorming-process)
