### ISSUE TITLE
MS3: Explanation of the decision process

### ISSUE THREAD

**Issue by jsurrea** [UniSchedule/Wiki#34]
You must explain the decision process based on what you have learned to select one idea (i.e., converge and divergence strategies). Include the process that you used to choose the idea for the semester. It must be clear that you used one of the techniques taught in class.

**Comment by SnowArtz** [comment]
We documentated the proposal solution for the selected problem at [Wiki](https://github.com/ISIS3510-202410-Team-13/Wiki/wiki/S1_MS3#description-of-the-solution)
