### ISSUE TITLE
MS3: Explanation and evidence of the brainstorming process.

### ISSUE THREAD

**Issue by iGotty** [UniSchedule/Wiki#36]
We must deliver a thorough explanation and evidence of our brainstorming process. We must describe our process and list the ideas derived from it. Include evidence (e.g., screenshots) of this task and apply the concepts taught in class.

**Comment by jsurrea** [comment]
Assigned to sub-group: @lfrancom10 and @jsurrea

**Comment by jsurrea** [comment]
Completed at [620542f](https://github.com/ISIS3510-202410-Team-13/Wiki/wiki/S1_MS3/620542f03761ba3d04a35b9c17075d5338ef2bb4)
