### ISSUE TITLE
Identify 3 YX personas

### ISSUE THREAD

**Issue by SnowArtz** [UniSchedule/Wiki#39]
Identify 3 YX personas following the guidelines explained in the C2 workshop. Describe each one of them. We must use the template
provided by the course.

**Comment by SnowArtz** [comment]
Together with @iGotty identify and fulfilled the Peronaformat related with Teaching Assitant

**Comment by lfrancom10** [comment]
With my partner @jsurrea, we made the person map of the student Gabriela, who is a university student

**Comment by jdcastellanosb73** [comment]
Together with @Laudarias  identify and fulfilled the Perona format related with a student who wants to lunch with friends
