### ISSUE TITLE
Develop Empathy map of Prospective User - @lfrancom10

### ISSUE THREAD

**Issue by lfrancom10** [UniSchedule/Wiki#40]
Develop an empathy map corresponding to a prospective user. You should answer each question from the template accordingly and relate it to the prospective users. You must use the template provided by the coursee.

**Comment by jsurrea** [comment]
Completed at [c0a4c77](https://github.com/ISIS3510-202410-Team-13/Wiki/wiki/S1_MS3/c0a4c774849bf3d63990300b6efc67bace794659)
