### ISSUE TITLE
Description of the solution for the problem that you have selected

### ISSUE THREAD

**Issue by jdcastellanosb73** [UniSchedule/Wiki#42]
You must explain the decision process based on what you have
learned to select one idea (i.e., converge and divergence strategies). Include the
process that you used to choose the idea for the semester.

**Comment by jsurrea** [comment]
Completed at [cf1b960](https://github.com/ISIS3510-202410-Team-13/Wiki/wiki/S1_MS3/cf1b96010be36c365eb7a83ace32cc5fa29acd6c)
