### ISSUE TITLE
MS4: Write two short descriptions

### ISSUE THREAD

**Issue by Laudarias** [UniSchedule/Wiki#52]
Write one description for the problem selected and one for the proposed solution.
Essential deliverable, must be at the beginning of the page

**Comment by SnowArtz** [comment]
The descriptions of the problem and the solutions were documentated at [wiki](https://github.com/ISIS3510-202410-Team-13/Wiki/wiki/S1_MS4#description-of-the-problems-and-the-proposed-solution)
