### ISSUE TITLE
MS2: Create 2 Journey Maps

### ISSUE THREAD

**Issue by jsurrea** [UniSchedule/Wiki#6]
Observations:
- Follow the observational methodologies described on O1.
- Reflect the data collected on the interviews.
- Include images, photos, sketches.

**Comment by jsurrea** [comment]
Observations:
- Follow the observational methodologies described on O1.
- Reflect the data collected on the interviews.
- Include images, photos, sketches.

**Comment by iGotty** [comment]
The first journey map starts to be realized

**Comment by jsurrea** [comment]
See [d64e6f0](https://github.com/ISIS3510-202410-Team-13/Wiki/wiki/S1_MS2/d64e6f0b04614d1d8ffebced72b724348e9b8b46)
